export const categories = [
  "Any",
  "Single-player",
  "Steam Achievements",
  "Steam Trading Cards",
  "Steam Cloud",
  "Stats",
  "Multi-player",
  "PvP",
  "Shared/Split Screen PvP",
  "Co-op",
  "Shared/Split Screen Co-op",
  "Shared/Split Screen",
  "Full controller support",
  "Remote Play Together",
  "Downloadable Content",
  "Captions available",
  "Steam Leaderboards",
  "Partial Controller Support",
  "Remote Play on TV",
  "Online PvP",
  "Online Co-op",
  "In-App Purchases",
  "Cross-Platform Multiplayer",
  "Steam Workshop",
  "Includes level editor",
  "LAN PvP",
  "LAN Co-op",
  "Remote Play on Phone",
  "Remote Play on Tablet",
  "VR Supported",
  "HDR available",
  "MMO",
  "Tracked Controller Support",
  "VR Only",
  "Additional High-Quality Audio",
  "VR Support",
  "Commentary available",
];
