export const genres = [
  "Any",
  "Adventure",
  "Casual",
  "Indie",
  "Simulation",
  "Strategy",
  "RPG",
  "Early Access",
  "Racing",
  "Action",
  "Free to Play",
  "Massively Multiplayer",
  "Sports",
  "Audio Production",
  "Design & Illustration",
  "Photo Editing",
  "Utilities",
  "Video Production",
  "Game Development",
];
